# Generated by Django 4.1.9 on 2023-07-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CRM", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="connect_accepted",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="connects_sent",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
