# Generated by Django 4.2.3 on 2023-08-28 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_account_campaign_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excel_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.JSONField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.campaign')),
            ],
        ),
    ]
