# Generated by Django 4.2.3 on 2023-10-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CRM", "0004_excel_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="daily_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="contact_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="intro_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
