# Generated by Django 4.2.3 on 2023-11-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CRM", "0005_campaign_daily_count_profile_contact_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="status",
            field=models.CharField(default="Paused", max_length=255),
        ),
    ]
