# Generated by Django 4.2.3 on 2023-11-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CRM", "0006_account_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="category",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
