# Generated by Django 4.2.3 on 2023-11-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CRM", "0007_campaign_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="search_value",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
