# Generated by Django 4.2.3 on 2023-11-17 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("CRM", "0008_campaign_search_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="CRM.campaign",
            ),
        ),
    ]
