# Generated by Django 4.2.3 on 2023-11-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CRM", "0009_alter_profile_campaign"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="last_communication",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
