# Generated by Django 4.2.3 on 2023-11-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CRM", "0010_profile_last_communication"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=255)),
                ("prompt", models.TextField()),
            ],
        ),
    ]
