# Generated by Django 4.2.3 on 2024-01-01 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0013_alter_linkedin_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excel_file',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CRM.campaign'),
        ),
    ]
