# Generated by Django 4.2.3 on 2024-01-03 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0014_alter_excel_file_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='excel_file',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 3, 15, 55, 41, 980025, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
