# Generated by Django 4.2.3 on 2024-01-22 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CRM", "0015_excel_file_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="restrict_view",
            field=models.CharField(default="enabled", max_length=255),
        ),
        migrations.AlterField(
            model_name="excel_file",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2024, 1, 22, 12, 44, 53, 850942, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
