# Generated by Django 4.2.3 on 2024-01-11 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0016_campaign_boolean_search_campaign_max_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='batch_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='excel_file',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 11, 17, 9, 54, 701968, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
