# Generated by Django 4.2.3 on 2024-01-23 20:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("CRM", "0016_account_restrict_view_alter_excel_file_created_at"),
        ("CRM", "0017_campaign_batch_size_alter_excel_file_created_at"),
    ]

    operations = []
