# Generated by Django 4.2.3 on 2024-01-23 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CRM", "0018_merge_20240123_2052"),
    ]

    operations = [
        migrations.AddField(
            model_name="excel_file",
            name="duplicate",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="excel_file",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="excel_file",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2024, 1, 23, 20, 53, 2, 523532, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
