# Generated by Django 4.2.3 on 2024-01-26 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0019_excel_file_duplicate_excel_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='total_profile_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='excel_file',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 26, 20, 17, 22, 700839, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
