# Generated by Django 4.2.3 on 2024-01-27 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0020_campaign_status_campaign_total_profile_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='excel_file',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 27, 18, 48, 22, 408249, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
