# Generated by Django 4.2.3 on 2024-02-07 12:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CRM', '0021_alter_campaign_status_alter_excel_file_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excel_file',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 7, 12, 36, 14, 540559, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.CreateModel(
            name='ScrapperProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxyip', models.CharField(max_length=255)),
                ('proxyport', models.CharField(max_length=255)),
                ('proxyuser', models.CharField(max_length=255)),
                ('proxypass', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
