# Generated by Django 4.2.3 on 2024-02-11 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CRM", "0022_alter_excel_file_created_at_scrapperproxy"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkedin_user",
            name="cookies",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="excel_file",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2024, 2, 11, 11, 31, 36, 118932, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
