# Generated by Django 4.1.9 on 2024-02-14 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CRM", "0023_linkedin_user_cookies_alter_excel_file_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="jd_status",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="excel_file",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2024, 2, 14, 9, 59, 23, 377004, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
