# Generated by Django 4.2.3 on 2024-02-18 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CRM", "0024_profile_jd_status_alter_excel_file_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="capacity_limit",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="excel_file",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2024, 2, 18, 13, 33, 23, 316617, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
