# Generated by Django 4.2.3 on 2024-02-19 19:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0025_account_capacity_limit_alter_excel_file_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excel_file',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 19, 19, 14, 41, 897485, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.CreateModel(
            name='UserMetricsDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 19, 19, 14, 41, 900475, tzinfo=datetime.timezone.utc), null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CRM.account')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CRM.linkedin_user')),
            ],
        ),
    ]
