# Generated by Django 4.2.3 on 2024-02-19 19:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CRM', '0026_alter_excel_file_created_at_usermetricsdistribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excel_file',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 19, 19, 59, 7, 522641, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='usermetricsdistribution',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 19, 19, 59, 7, 525633, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='usermetricsdistribution',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
