# Generated by Django 5.0.3 on 2024-03-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CRM", "0028_alter_excel_file_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="boolean_search",
            field=models.TextField(blank=True, null=True),
        ),
    ]
