# Generated by Django 5.0.3 on 2024-03-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CRM", "0030_campaign_changed_jobs_campaign_company_head_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="changed_jobs",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="posted_on_linkedin",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
