# Generated by Django 5.0.3 on 2024-03-25 09:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CRM", "0031_alter_campaign_changed_jobs_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="current_company",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=1026),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="current_job_title",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=1026),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="first_name",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=1026),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="geography",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=1026),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="groups",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=1026),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="industry",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=1026),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="last_name",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=1026),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="school",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=1026),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
