# Generated by Django 5.0.3 on 2024-04-04 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CRM", "0032_alter_campaign_current_company_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                (
                    "Linkedin_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CRM.linkedin_user",
                    ),
                ),
            ],
        ),
    ]
