# Generated by Django 5.0.3 on 2024-04-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CRM", "0033_savedsearch"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="autoscrapper",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
