# Generated by Django 5.0.3 on 2024-04-04 21:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("CRM", "0034_campaign_autoscrapper"),
    ]

    operations = [
        migrations.RenameField(
            model_name="savedsearch",
            old_name="Linkedin_user",
            new_name="linkedinuser",
        ),
    ]
