# Generated by Django 5.0.3 on 2024-04-05 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CRM", "0036_alter_savedsearch_link_alter_savedsearch_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="saved_search",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="CRM.savedsearch",
            ),
        ),
    ]
