# Generated by Django 5.0.3 on 2024-04-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CRM", "0037_campaign_saved_search"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="maxpage",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="minpage",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
