# Generated by Django 4.2.3 on 2024-04-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0038_campaign_maxpage_campaign_minpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='redirected_link',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
