# Generated by Django 4.2.3 on 2024-04-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0041_profile_expat_status_profile_gender_scrapperlogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
