# Generated by Django 4.2.3 on 2024-04-30 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0043_leadslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='lead_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CRM.leadslist'),
        ),
    ]
