# Generated by Django 4.2.3 on 2024-05-01 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CRM', '0044_campaign_lead_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='current_company',
            new_name='exclude_nationality_list',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='changed_jobs',
            new_name='expat',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='current_job_title',
            new_name='include_nationality_list',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='posted_on_linkedin',
            new_name='local',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='company_head_count',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='connection',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='function',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='geography',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='profile_language',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='school',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='seniority_level',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='years_of_experience',
        ),
        migrations.AddField(
            model_name='campaign',
            name='max_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='min_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='excel_file',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
