# Generated by Django 4.2.3 on 2024-05-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0045_rename_current_company_campaign_exclude_nationality_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='gender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
