# Generated by Django 4.2.3 on 2024-05-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0046_campaign_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lead_status',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
