# Generated by Django 4.2.3 on 2024-05-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0048_profile_lead_last_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='gpt_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
