# Generated by Django 4.2.3 on 2024-07-31 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0049_campaign_gpt_prompt'),
        ('CRM', '0049_note'),
    ]

    operations = [
    ]
