# Generated by Django 4.2.3 on 2024-07-31 15:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0050_merge_0049_campaign_gpt_prompt_0049_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='exclude_first_names_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1026), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='campaign',
            name='include_first_names_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1026), blank=True, null=True, size=None),
        ),
    ]
