# Generated by Django 4.2.3 on 2024-08-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0051_campaign_exclude_first_names_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='nationality_batch',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
